language: node_js

node_js:
  - "6"

cache:
  directories:
    - node_modules

addons:
  # This gives us Firefox, for the karma tests. Feel free to set a minimum version here.
  firefox: "latest"

before_install:
  # This is so Firefox can run with karma
  # see https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16 -extension RANDR"
  - sleep 3

# This gives us Firefox, for the karma tests
install:
  - npm config set spin false
  - npm install

script:
  - npm test

# deploy:

# Turns off email notifications for travis. Turn this back on if you want them.
notifications:
  email: false
