language: node_js

node_js:
  - "6"

cache:
  directories:
    - node_modules

addons:
  # This gives us Firefox, for the karma tests. Feel free to set a minimum version here.
  firefox: "latest"

# This gives us Firefox, for the karma tests
install:
  - npm config set spin false
  - npm install

script:
  - npm test

# deploy:

# Turns off email notifications for travis. Turn this back on if you want them.
notifications:
  email: false
